FROM postgres:latest

RUN apt update && apt install -y nano

ENV POSTGRES_USER miguel
ENV POSTGRES_PASSWORD 12345
ENV POSTGRES_DB database_inicial_miguel

# Puerto por defecto de PostgreSQL
EXPOSE 5432

# Volumen para copiar las bases de datos
VOLUME /var/lib/postgresql/data

